---
title: "Project 2 by Danny Pham"
output: html_notebook
---
### Part 1
```{r}
scores<-read.table("testscoredata.txt", header = TRUE)[,-1]
scores
```

```{r}
summary(manova(cbind(math, reading) ~ sex, data = scores), test = "Hotelling")
```

### Part 2
```{r}
female<-data.frame(
  sport=c('B','B','B','B','B','T','T','T','T','S','S','S','S','S','S'),
  height=c(66,65,68,64,67,63,61,62,60,62,65,63,62,63.5,66),
  jump=c(27,29,26,29,29,23,26,23,26,23,21,21,23,22,21.5)
)
female
```
```{r}
summary(manova(cbind(height, jump) ~ sport, data = female), test = "Wilks")
```

```{r}
chisplot <- function(x) {
  if (!is.matrix(x))
    stop("x is not a matrix")
  ### determine dimensions
  n <- nrow(x)
  p <- ncol(x)
  xbar <- apply(x, 2, mean)
  S <- var(x)
  S <- solve(S)
  index <- (1:n) / (n + 1)
  xcent <- t(t(x) - xbar)
  di <- apply(xcent, 1, function(x, S)
    x %*% S %*% x, S)
  quant <- qchisq(index, p)
  plot(
    quant,
    sort(di),
    ylab = "Ordered distances",
    xlab = "Chi-square quantile",
    lwd = 2,
    pch = 1
  )
}
```

```{r}
chisplot(residuals(manova(cbind(height, jump) ~ sport, data = female), test = "Wilks"))
```

```{r}
by(female[,-1], sport, var)
```


```{r}
aggregate(x = female$height,
          by = list(female$sport),
          FUN = mean)

aggregate(x = female$jump,
          by = list(female$sport),
          FUN = mean)        
```

